### ISSUE TITLE
Never ending polling on the search results page

### ISSUE THREAD

**Issue by olivierobert** [junan/data_extractor#10]
![Data_Extractor](https://user-images.githubusercontent.com/696529/56555712-e82e0600-65bf-11e9-9eea-e65103b42628.jpg)

Probably adding a simple check that for every row (each search term) all the columns are filled with data could do the trick

**Comment by junan** [comment]
> Never ending polling on the search results page

It actually does polling request 100 times, after that it stops and it also immediately stops if user visits another page

> Probably adding a simple check that for every row (each search term) all the columns are filled with data could do the trick

Thanks for the nice suggestion, I refactored  the code accordingly. Commit https://github.com/junan/data_extractor/commit/5bc627170b6e96bec3c9275fc502dd9da52ae6d8
