### ISSUE TITLE
Why not picking a newer version of Ruby?

### ISSUE THREAD

**Issue by olivierobert** [junan/data_extractor#5]
While it's not compulsory, I am wondering why not picking Ruby 2.6.x for the project.

**Comment by junan** [comment]
@olivierobert Default ruby version of my machine is `2.4.2`. Thats why I created the project with this version. I just upgraded the ruby version with `2.6.1` in this commit https://github.com/junan/data_extractor/commit/d2d76361b86223ffa20a08e114dc39cca028e9d1

**Comment by olivierobert** [comment]
Understood. It would be good to open PRs for changes too.

**Comment by junan** [comment]
@olivierobert Sorry, I did not know that I need to open PRs for changes
