### ISSUE TITLE
Breaking apart validations for Search model

### ISSUE THREAD

**Issue by olivierobert** [junan/data_extractor#6]
The custom validation is `app/models/search.rb` is rather unsatisifying as it does not stick to the single responsibility principle as it's checking for both presence and type so breaking into would be better (note that we still need to check for `csv.attached?` before checking the type):

```
class Search < ApplicationRecord
  #...
  has_one_attached :csv

  validate :csv_presence
  validate :csv_type, if: -> { csv.attached? }

  private

  def csv_presence
    unless csv.attached?
      errors.add(:csv, "can't be blank")
    end
  end

  def csv_type
    unless csv.content_type == 'text/csv'
      errors.add(:csv, 'needs to be in csv format')
    end
  end
end
```

I understand there are some limitations on Active Storage of validations this point, so another solution would be to use https://github.com/musaffa/file_validators.

> prefer using `unless` instead of the negative conditional

**Comment by junan** [comment]
> The custom validation is `app/models/search.rb` is rather unsatisifying as it does not stick to the single responsibility principle as it's checking for both presence and type so breaking into would be better (note that we still need to check for `csv.attached?` before checking the type):

You are correct! Thanks for pointing me in the right direction. I picked your suggested code as it is better and cleaner. Commit https://github.com/junan/data_extractor/commit/725c0e1e7838271deb0095518387ac39f0e47de5 

> I understand there are some limitations on Active Storage of validations this point, so another solution would be to use https://github.com/musaffa/file_validators.

When I was doing the validation part I also found the gem but did not use it as custom validation covering my need.
