### ISSUE TITLE
Externalize parsing Google Search Result Page (SERP) from the Job class

### ISSUE THREAD

**Issue by olivierobert** [junan/data_extractor#7]
Currently, `SearchRequestJob` is in charge of the page of both performing the job orchestration with complex rules for rescheduling and the arsing of the SERP. That's way too much responsibility. 

I recommend to externalize the page request and parsing with Nologiri to another object as done similarly for `SearchServiceJob` + `SearchService`.

**Comment by junan** [comment]
> Currently, `SearchRequestJob` is in charge of the page of both performing the job orchestration with complex rules for rescheduling and the arsing of the SERP. That's way too much responsibility. 

@olivierobert You are correct! It was carrying too much responsibilities

> I recommend to externalize the page request and parsing with Nologiri to another object as done similarly for `SearchServiceJob` + `SearchService`.

Thanks for your nice suggestion. I splitted it into service objects in this commit https://github.com/junan/data_extractor/commit/01204faeff600e9f9759e47efc2da64383e76c66

**Comment by olivierobert** [comment]
Looks good. Here again a PR would have been welcome.

**Comment by junan** [comment]
@olivierobert Sorry, I did not know that had to open PRs for changes
