### ISSUE TITLE
Awkward and maybe dangerous sleep behaviour in SearchService

### ISSUE THREAD

**Issue by olivierobert** [junan/data_extractor#8]
Instead of adding a random sleep time, how about delaying the job itself using a wait configuration:

```
class SearchService
  #...

  def call
     #...
    CSV.foreach(csv_path, headers: false, liberal_parsing: true) do |row|
      row.each do |keyword|
        # ...
        SearchRequestJob.set(wait: 5.seconds.perform_later(data_set.id)
      end
    end
  end
end
```

Read more: https://github.com/rails/rails/blob/master/activejob/lib/active_job/core.rb#L56

**Comment by junan** [comment]
@olivierobert I liked your suggested way and I also like to extend it by supporting different delay time  for each `data_set`
```ruby
class SearchService
  #...

  def call
     #...
    interval = 0
    CSV.foreach(csv_path, headers: false, liberal_parsing: true) do |row|
      row.each do |keyword|
        # ...

        SearchRequestJob.set(wait: interval.seconds).perform_later(data_set.id)
        interval += 5
      end
    end
  end
end
```
It will schedule the jobs with time gaps and ensure's it will not create many search request at a same time
<img width="1254" alt="Screen Shot 2019-04-25 at 1 10 19 AM" src="https://user-images.githubusercontent.com/6076762/56687874-0ea38c80-66f9-11e9-870e-f201da7c83de.png">

Without the time gap support it will create many search request at a same time
<img width="1222" alt="Screen Shot 2019-04-25 at 1 04 04 AM" src="https://user-images.githubusercontent.com/6076762/56688107-a73a0c80-66f9-11e9-88b7-280bc4f7640c.png">

What do you think about it?

**Comment by olivierobert** [comment]
I think that would work and it's sufficient enough :-)

**Comment by junan** [comment]
@olivierobert I already updated it in the polling data commit https://github.com/junan/data_extractor/commit/5bc627170b6e96bec3c9275fc502dd9da52ae6d8. Is it ok for you?

**Comment by olivierobert** [comment]
@junan Yes it is -)
