### ISSUE TITLE
Render the stored content into an iframe

### ISSUE THREAD

**Issue by olivierobert** [junan/data_extractor#9]
![Data_Extractor](https://user-images.githubusercontent.com/696529/56555609-a7ce8800-65bf-11e9-9505-c84bb5455916.jpg)

In order to make the store content usable, it would be better to actually render it 😅

**Comment by junan** [comment]
Thanks, I rendered it in this commit https://github.com/junan/data_extractor/commit/6e7913a635c8aecdf6bd9b3f393534bc09593343 😄

**Comment by olivierobert** [comment]
Good call to use a data URI 👍

**Comment by junan** [comment]
@olivierobert Thanks!
